AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trainocate-ecommerce-serverless

  Sample SAM Template for trainocate-ecommerce-serverless

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - Stage
      - Prod
      - Test
      - Dev
    Default: Dev
    Description: Stage to be appended to resource names

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Environment:
      Variables:
        TABLE_NAME_COURSES: courses

Resources:

  FetchCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch_courses/
      Handler: app.lambda_handler
      Events:
        FetchCourses:
          Type: Api
          Properties:
            Path: /courses
            Method: get

  SaveCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_course/
      Handler: app.lambda_handler
      Events:
        CreateCourse:
          Type: Api
          Properties:
            Path: /courses
            Method: post

  ShowCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: show_course/
      Handler: app.lambda_handler
      Events:
        CreateCourse:
          Type: Api
          Properties:
            Path: /courses/{code}
            Method: get

  DestroyCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: destroy_course/
      Handler: app.lambda_handler
      Events:
        CreateCourse:
          Type: Api
          Properties:
            Path: /courses
            Method: delete

Outputs:
  ProdApi:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
